# This is a basic workflow to help you get started with Actions

name: update latest release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: build latest release
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: pack latest release
        run: |
          echo "Release updated."

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            rc/*
            VPN/*
            init/*
      - uses: actions/checkout@v2
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: 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
          gist_id: 96bd7e4b84fc6b22f994b34843908bf2
          gist_description: "init script"
          gist_file_name: psprofile
          file_path: ./init/rc/Microsoft.PowerShell_profile.ps1